// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#ifndef WINRT_Windows_Media_Render_H
#define WINRT_Windows_Media_Render_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.3.4.5"), "Mismatched C++/WinRT headers.");
#include "winrt/Windows.Media.h"
#include "winrt/impl/Windows.Media.Render.2.h"
namespace winrt::impl
{
}
namespace winrt::Windows::Media::Render
{
}
namespace std
{
}
#endif
