// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.3.4.5

#ifndef WINRT_Windows_Graphics_Effects_2_H
#define WINRT_Windows_Graphics_Effects_2_H
#include "winrt/impl/Windows.Graphics.Effects.1.h"
namespace winrt::Windows::Graphics::Effects
{
}
#endif
